### ISSUE TITLE
Schema error after upgrade "purchase_order_number"

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/marello#19] opened 2017-04-21 09:24 UTC
After upgrading to RC I had to rename manually "purchaseOrderNumber" to "purchase_order_number" in "marello_purchase_order".

**Comment by 24198** [comment] 2018-01-08 09:39
Closing issue since this RC is no longer maintained and therefore the issue is irrelevant.

**Closed as completed by 24198** 2018-01-08 09:39 UTC
