### ISSUE TITLE
Schema error after upgrade "channel_type"

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/marello#17] opened 2017-04-21 09:18 UTC
After upgrading to RC I had to rename manually field "channeltype" to "channel_type" in table "marello_sales_sales_channel".

**Comment by 24198** [comment] 2018-01-08 09:39
Closing issue since this RC is no longer maintained and therefore the issue is irrelevant.

**Closed as completed by 24198** 2018-01-08 09:39 UTC
