### ISSUE TITLE
Call to undefined method getAssociationTargetClass()

### ISSUE THREAD

**Issue by dainiusgliebus** [marellocommerce/marello#56] opened 2019-05-10 11:54 UTC
Oro: 3.1.6
Marello 2.0.0

Fatal error: Call to undefined method Marello\Bundle\CoreBundle\Serializer\EntitySerializer::getAssociationTargetClass() in vendor/marellocommerce/marello/src/Marello/Bundle/CoreBundle/Serializer/EntitySerializer.php:119

**Comment by 24198** [comment] 2019-05-21 08:46
Hi @dainiusgliebus,

Thank you for reporting, sorry I wasn't able to get back to you earlier! 
We have confirmed that there is fact a bug in the serializer regarding the AssociationTargetClass method. The EntitySerializer is not in use anymore since we've removed all routes for the REST Api for Marello 2.0.0 (deprecated by Oro) and moved most of the eindpoints to the REST JSON Api. We should've removed the serializer which we have failed to do so.

However, we'll fix the undefined method issue on the 2.0 branch and mark it deprecated for future reminder.

Thanks again for reporting.

Kind Regards,

Jaimy Casteleijn

**Comment by 24198** [comment] 2019-05-23 10:41
Hi @dainiusgliebus,

We've fixed the undefined method call in the EntitySerializer with commit https://github.com/marellocommerce/marello/commit/7139917230723d97b9b8c99e27dcd5c3f7d2e8e1 which has been merged to master and 2.0 branch.

Thanks for Reporting!


Kind Regards,

Jaimy Casteleijn

**Closed as completed by 24198** 2019-05-23 10:41 UTC
Labels: bug
