### ISSUE TITLE
Schema error after upgrade. Missing field "preferred_supplier_id"

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/marello#18] opened 2017-04-21 09:19 UTC
After upgrade to RC I had to add manually new field "preferred_supplier_id" in "marello_product_product".

**Comment by 24198** [comment] 2018-01-08 09:39
Closing issue since this RC is no longer maintained and therefore the issue is irrelevant.

**Closed as completed by 24198** 2018-01-08 09:39 UTC
