### ISSUE TITLE
Schema error after upgrade. Camel Case field names

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/marello#20] opened 2017-04-21 09:30 UTC
Generally there is a field naming problem after upgrading to RC.

I had to rename all fields of "marello_order_customer" from CamelCase to underscore naming. The same here #19 #17 #18

**Comment by 24198** [comment] 2018-01-08 09:39
Closing issue since this RC is no longer maintained and therefore the issue is irrelevant.

**Closed as completed by 24198** 2018-01-08 09:39 UTC
